# This is a basic workflow to help you get started with Actions

name: Terraform Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Allow the workflow to request an ID token

jobs:
  terraform_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login (Dev)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (Dev)
        run: terraform init
        working-directory: ./dev

      - name: Terraform Validate (Dev)
        run: terraform validate
        working-directory: ./dev

      - name: Terraform Plan (Dev)
        run: terraform plan -var-file=dev/terraform.tfvars
        working-directory: ./dev

      - name: Terraform Apply (Dev)
        run: terraform apply -auto-approve -var-file=dev/terraform.tfvars
        working-directory: ./dev

  terraform_qa:
    runs-on: ubuntu-latest
    needs: [terraform_dev]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login (QA)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (QA)
        run: terraform init
        working-directory: ./qa

      - name: Terraform Validate (QA)
        run: terraform validate
        working-directory: ./qa

      - name: Terraform Plan (QA)
        run: terraform plan -var-file=qa/terraform.tfvars
        working-directory: ./qa

      - name: Terraform Apply (QA)
        run: terraform apply -auto-approve -var-file=qa/terraform.tfvars
        working-directory: ./qa

  terraform_prod:
    runs-on: ubuntu-latest
    needs: [terraform_dev, terraform_qa]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login (Prod)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (Prod)
        run: terraform init
        working-directory: ./prod

      - name: Terraform Validate (Prod)
        run: terraform validate
        working-directory: ./prod

      - name: Terraform Plan (Prod)
        run: terraform plan -var-file=prod/terraform.tfvars
        working-directory: ./prod

      - name: Terraform Apply (Prod)
        run: terraform apply -auto-approve -var-file=prod/terraform.tfvars
        working-directory: ./prod
