# This is a basic workflow to help you get started with Actions

name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    # Step 1: Checkout the repository
    - name: Checkout the repository
      uses: actions/checkout@v4

    # Step 2: Check Azure CLI Version
    - name: Check Azure CLI Version
      run: |
        az --version

    # Step 3: Log in to Azure using Service Principal
    - name: Log in to Azure
      run: |
        az login --service-principal \
          -u ${{ secrets.AZURE_CLIENT_ID }} \
          -p ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}
        az account set --subscription ${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}

    # Step 4: Debug Azure Login Status
    - name: Verify Azure Login
      run: |
        az account show

    # Step 5: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    # Step 6: Terraform Init
    - name: Terraform Init
      run: terraform init

    # Step 7: Terraform Plan
    - name: Terraform Plan
      run: terraform plan -out=tfplan.binary

    # Step 8: Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
