# This is a basic workflow to help you get started with Actions

name: Terraform Deployment

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Grant write permissions for id-token to allow login to Azure

    strategy:
      matrix:
        environment: [dev, qa, prod]  # Sequential execution of dev, qa, and prod environments

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Azure Login using Service Principal Credentials from GitHub Secrets
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}  # Added subscription-id

      # Step 3: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ matrix.environment }}

      # Step 5: Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ matrix.environment }}

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars
        working-directory: ${{ matrix.environment }}

      # Step 7: Terraform Apply (Only for QA and PROD)
      - name: Terraform Apply (Only for QA and PROD)
        if: matrix.environment != 'dev'
        run: terraform apply -auto-approve -var-file=terraform.tfvars
        working-directory: ${{ matrix.environment }}
