# This is a basic workflow to help you get started with Actions

name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        environment: [dev, qa, prod]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Environment Directories
        run: mkdir -p ${{ matrix.environment }}

      - name: Clear Azure CLI Config
        run: |
           az account clear
           az logout


      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

          allow-no-subscriptions: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ matrix.environment }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ matrix.environment }}

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars
        working-directory: ${{ matrix.environment }}

      - name: Terraform Apply (Only for QA and PROD)
        if: matrix.environment != 'dev'
        run: terraform apply -auto-approve -var-file=terraform.tfvars
        working-directory: ${{ matrix.environment }}
